// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3z84FNdDcCMe9vULiNZ8YjputdlHZY-s',
    appId: '1:97928218656:web:57b13fdc50b56dfa4f1445',
    messagingSenderId: '97928218656',
    projectId: 'news-ac8bc',
    authDomain: 'news-ac8bc.firebaseapp.com',
    storageBucket: 'news-ac8bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA__R8hpRgJBc6yyU9aeqOT8SCrOBhmcbQ',
    appId: '1:97928218656:android:78a1357054e5f1c44f1445',
    messagingSenderId: '97928218656',
    projectId: 'news-ac8bc',
    storageBucket: 'news-ac8bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqZvi_IJi1zcYDftucswj6br9l3jSSS9M',
    appId: '1:97928218656:ios:ad56cefaca80afe64f1445',
    messagingSenderId: '97928218656',
    projectId: 'news-ac8bc',
    storageBucket: 'news-ac8bc.appspot.com',
    iosClientId: '97928218656-k2tgt5rrfnish2vv16e46bql1nrttm76.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqZvi_IJi1zcYDftucswj6br9l3jSSS9M',
    appId: '1:97928218656:ios:78446892a325eeb14f1445',
    messagingSenderId: '97928218656',
    projectId: 'news-ac8bc',
    storageBucket: 'news-ac8bc.appspot.com',
    iosClientId: '97928218656-srcljkerocovjh854ilkrsngbp5mfsrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
